name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  get_it: ^8.0.3
  geolocator: ^13.0.2
  go_router: ^14.6.3
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.14


flutter:

 
  uses-material-design: true

  
